# PUll from Docker Hub image nginx. in this case it is latest
FROM nginx:latest

# Copy from ./www to /usr/share/nginx/html
COPY index.html /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf
