apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      nginx: demo
  template:
    metadata:
      labels:
        nginx: demo
    spec:
      containers:
      - name: nginx-demo-test
        image: kube_nginx:latest
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    nginx: demo
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001

