version: '3.7'
services:
  proxy:
    build: nginx
    container_name: nginx_reverse_proxy
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 80:80
    depends_on: 
     - joomla
     - jenkins

  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: password

  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  jenkins:
    image: jenkins/jenkins
    volumes: 
      - jenkins_home:/var/jenkins_home
    ports:
      - 9090:8080
      - 50000:50000

networks:
  default:
    external: true
    name: composer_default

volumes: 
  jenkins_home:
