version: "3.7"
services:
  jenkins:
    build: jenkins
    expose: 
      - 8080:8080
      - 50000:50000

  sonarqube:
    build: sonarqube
    volumes: 
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    expose: 
      - 9000:9000

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:

